---
title: "REWOD_PIT_RM"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r preliminary stuff, echo=TRUE, include=FALSE}
# load library
library(lme4)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(plyr)
```
## R code for FOR REWOD_PIT
# last modified on Nov 2018 by David
#SETUP
```{r}
# Set working directory
analysis_path <- '~/rewod/DATABASES/'# for this to work the script needs to be sourced
setwd(analysis_path)

# open dataset
REWOD_PIT <- read.delim(file.path(analysis_path,'REWOD_PIT.txt'), header = T, sep ='') # read in dataset

## subsetting into 3 differents tasks
REWOD_PIT.all <- REWOD_PIT
REWOD_RIM <- subset (REWOD_PIT.all,task == 'Reminder') 
REWOD_PE <- subset (REWOD_PIT.all,task == 'Partial_Extinction') 
REWOD_PIT <- subset (REWOD_PIT.all,task == 'PIT') 


# define factors
REWOD_RIM$id               <- factor(REWOD_RIM$id)
REWOD_RIM$trial            <- factor(REWOD_RIM$trial)
REWOD_RIM$task              <- factor(REWOD_RIM$task)
REWOD_RIM$session          <- factor(REWOD_RIM$session)
REWOD_RIM$reward        <- factor(REWOD_RIM$reward)

REWOD_PE$id               <- factor(REWOD_PE$id)
REWOD_PE$trial            <- factor(REWOD_PE$trial)
REWOD_PE$task              <- factor(REWOD_PE$task)
REWOD_PE$session          <- factor(REWOD_PE$session)
REWOD_PE$reward        <- factor(REWOD_PE$reward)

REWOD_PIT$id               <- factor(REWOD_PIT$id)
#REWOD_PIT$trial            <- factor(REWOD_PIT$trial)
REWOD_PIT$task              <- factor(REWOD_PIT$task)
REWOD_PIT$session          <- factor(REWOD_PIT$session)
```

# PLOTS


##plot (non-averaged per participant) 
```{r boxplots n_grips distribution, fig.align = "center"}
#n_grips RIM
boxplot(REWOD_RIM$n_grips ~ REWOD_RIM$trial, las = 1)
#n_grips PE
boxplot(REWOD_PE$n_grips ~ REWOD_PE$trial, las = 1)
#n_grips PIT
boxplot(REWOD_PIT$n_grips ~ REWOD_PIT$trial, las = 1)
```

## plot overall effect
```{r boxplots overall effect, fig.align = "center"}
# get means by trial
RIM.bt = ddply(REWOD_RIM, .(trial), summarise,  n_grips = mean(n_grips, na.rm = TRUE)) 
PE.bt = ddply(REWOD_PE, .(trial), summarise,  n_grips = mean(n_grips, na.rm = TRUE)) 
PIT.bt = ddply(REWOD_PIT, .(trial), summarise,  n_grips = mean(n_grips, na.rm = TRUE)) 
# get means by trial & condition
PIT.bct = ddply(REWOD_PIT, .(condition, trial), summarise,  n_grips = mean(n_grips, na.rm = TRUE)) 

# get means by participant 
RIM.bs = ddply(REWOD_RIM, .(id, trial), summarise, n_grips = mean(n_grips, na.rm = TRUE)) #not condition
PE.bs = ddply(REWOD_PE, .(id, trial), summarise, n_grips = mean(n_grips, na.rm = TRUE)) #not condition
PIT.bs = ddply(REWOD_PIT, .(id, condition, trial), summarise, n_grips = mean(n_grips, na.rm = TRUE)) 

# ngrips average per trial
boxplot(RIM.bt$n_grips ~ RIM.bt$trial, las = 1)
boxplot(PE.bt$n_grips ~ PE.bt$trial, las = 1)
boxplot(PIT.bt$n_grips ~ PIT.bt$trial, las = 1)

```

##plot n_grips to see the trajectory of learning (overall average by trials)
```{r, fig.align = "center"}
ggplot(PIT.bt, aes(x = trial, y = n_grips, fill = I('royalblue1'), color = I('royalblue4'))) +
  geom_point() + geom_line(group=1) +
  guides(color = "none", fill = "none") +
  guides(color = "none", fill = "none") +
  theme_bw() +
  labs(
    title = "number of grips by time",
    x = "Trial",
    y = "number of grips"
  )

#OR different representation
ggplotRegression <- function (fit) {
  
  ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
    geom_point() +
    stat_smooth(method = "lm", col = "red") +
    labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                       "Intercept =",signif(fit$coef[[1]],5 ),
                       " Slope =",signif(fit$coef[[2]], 5),
                       " P =",signif(summary(fit)$coef[2,4], 5)))
}

# plot number of grips by time with regression lign
ggplotRegression(lm(n_grips ~ trial, data = PIT.bt))
```

##plot n_grips to see the trajectory of learning (overall average by trials) by conditions
```{r, fig.align = "center"}
ggplot(PIT.bct, aes(x = trial, y = n_grips, color = condition)) +
  geom_point() +
  geom_line(aes(group = condition), alpha = .3, size = 1) +
  scale_colour_manual("", 
                      values = c("CSplus"="green", "CSminus"="red", "Baseline"="blue")) +
  theme_bw() +
  labs(
    title = "number of grips By Time By condition",
    x = "Trial",
    y = "number of grips"
  )

# plot number of grips by time by condition with regression lign
ggplotRegression(lm(n_grips ~ trial*condition, data = PIT.bct)) + 
  facet_wrap(~condition)
```

# ANALYSIS


## 1. number of grips: are participants gripping more on the CSplus condition? 
```{r}
#factorise trial
REWOD_PIT$trial            <- factor(REWOD_PIT$trial)

#contrasts
REWOD_PIT$cvalue[REWOD_PIT$condition== 'CSplus']     <- 2
REWOD_PIT$cvalue[REWOD_PIT$condition== 'CSminus']     <- -1
REWOD_PIT$cvalue[REWOD_PIT$condition== 'Baseline']     <- -1
REWOD_PIT$cvalue       <- factor(REWOD_PIT$cvalue)

# lmer analyis ~ condition 
main.n_grips = lmer(n_grips ~ cvalue + (1+cvalue|id) + (1|trial), data = REWOD_PIT, REML = FALSE)
anova(main.n_grips)

# quick check with classical anova (! this is not reliable)
summary(aov(n_grips ~ cvalue + Error(id / (cvalue)), data = REWOD_PIT))

# model comparison
main.n_grips.0 = lmer(n_grips ~ (1|id) + (1|trial), data = REWOD_PIT, REML = FALSE)
anova(main.n_grips.0, main.n_grips, test = 'Chisq')

#sentence => main.n_grips is signifincatly better than the null model
```
